name: Publicar en PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Reemplaza "3.x" con la versión de Python que estés utilizando

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine

      - name: Construir el paquete
        run: python rutpy/setup.py sdist bdist_wheel

      - name: Publicar en PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # Configura el token de API de PyPI en los secretos del repositorio
        run: |
          python -m twine upload dist/*
